#!/bin/bash -x
# Pi-hole v6 installation script
# This script installs Pi-hole v6 which includes an embedded web server
# No longer requires lighttpd or PHP as Pi-hole v6 has these built-in
# 
# log user data output to /var/log/user-data.log
exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

# Function to log with timestamp
log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# Function to retry commands with exponential backoff
retry_command() {
    local max_attempts=5
    local delay=1
    local attempt=1
    
    while [ $attempt -le $max_attempts ]; do
        log_message "Attempt $attempt of $max_attempts: $*"
        if "$@"; then
            log_message "Command succeeded: $*"
            return 0
        else
            log_message "Command failed: $*"
            if [ $attempt -lt $max_attempts ]; then
                log_message "Waiting ${delay}s before retry..."
                sleep $delay
                delay=$((delay * 2))
            fi
            attempt=$((attempt + 1))
        fi
    done
    
    log_message "Command failed after $max_attempts attempts: $*"
    return 1
}

log_message "Starting Pi-hole v6 installation userdata script"

# upgrade packages
log_message "Updating package lists and upgrading system"
retry_command apt update -y
retry_command apt upgrade -y

# Install essential packages (removed lighttpd, php-* packages, but kept Lua)
log_message "Installing required packages"
retry_command apt install -y dialog unzip idn2 dns-root-data jq git binutils make wget python3-pip curl

# Install Lua packages (still needed for web interface extensions and processing)
log_message "Installing Lua packages for web interface processing"
retry_command apt install -y lua5.1 liblua5.1-0-dev lua-cjson

# not amazon linux, so need to build the package
log_message "Building and installing EFS utils"
retry_command git clone https://github.com/aws/efs-utils /tmp/efs-utils/
cd /tmp/efs-utils
retry_command ./build-deb.sh
retry_command apt -y install ./build/amazon-efs-utils*deb
retry_command pip3 install botocore --upgrade

# Create pihole directory and setup EFS mount with proper error handling
log_message "Setting up EFS mount for Pi-hole configuration"
mkdir -p /etc/pihole/
echo "$EFS_ID:/ /etc/pihole/ efs _netdev,noresvport,tls,iam,nofail 0 0" >>/etc/fstab

# Retry EFS mount with better error handling
log_message "Mounting EFS filesystem"
if ! retry_command mount -av; then
    log_message "EFS mount failed, but continuing with local storage"
    # Ensure directory exists even if EFS mount fails
    mkdir -p /etc/pihole/
fi

# Verify EFS mount status
if mountpoint -q /etc/pihole; then
    log_message "EFS successfully mounted to /etc/pihole"
else
    log_message "WARNING: EFS not mounted, using local storage"
fi

# Note: Pi-hole v6 configuration is handled via pihole.toml file created below

# Setup initial blocklists for v6
log_message "Setting up initial Pi-hole blocklists"
if [ ! -a /etc/pihole/adlists.list ]; then
	cat <<EOF >/etc/pihole/adlists.list
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://v.firebog.net/hosts/Admiral.txt
https://v.firebog.net/hosts/Easylist.txt
https://v.firebog.net/hosts/Prigent-Ads.txt
https://v.firebog.net/hosts/Prigent-Crypto.txt
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
EOF
fi

# Stop any existing lighttpd service (in case it's running from previous installations)
log_message "Stopping any existing lighttpd service"
systemctl stop lighttpd 2>/dev/null || true
systemctl disable lighttpd 2>/dev/null || true

# Create Pi-hole v6 TOML configuration for truly unattended installation
# Pi-hole v6 installer checks for pihole.toml OR setupVars.conf to detect fresh install
log_message "Creating Pi-hole v6 TOML configuration"
mkdir -p /etc/pihole

# Detect the primary network interface (exclude loopback)
PIHOLE_INTERFACE=$(ip -o link show up | awk -F': ' '!/lo/ {print $2; exit}')
log_message "Detected network interface: $PIHOLE_INTERFACE"
cat > /etc/pihole/pihole.toml << 'TOML_EOF'
# Pi-hole v6 configuration file
# Generated by CDK user-data script

[dns]
  upstreams = ["1.1.1.1", "1.0.0.1"]
  CNAMEdeepInspect = true
  blockESNI = true
  EDNS0ECS = true
  ignoreLocalhost = false
  showDNSSEC = true
  analyzeOnlyAandAAAA = false
  piholePTR = "PI.HOLE"
  replyWhenBusy = "ALLOW"
  blockTTL = 2
  domainNeeded = false
  expandHosts = false
  bogusPriv = false
  dnssec = false
TOML_EOF

# Append interface setting (needs variable substitution)
cat >> /etc/pihole/pihole.toml << EOF
  interface = "${PIHOLE_INTERFACE}"
EOF

cat >> /etc/pihole/pihole.toml << 'TOML_EOF'
  listeningMode = "ALL"
  queryLogging = true
  port = 53

  [dns.domain]
    name = "lan"
    local = true

  [dns.cache]
    size = 10000
    optimizer = 3600

  [dns.blocking]
    active = true
    mode = "NULL"

  [dns.specialDomains]
    mozillaCanary = true
    iCloudPrivateRelay = true

  [dns.rateLimit]
    count = 1000
    interval = 60

TOML_EOF

# Append reverse server settings (needs variable substitution)
cat >> /etc/pihole/pihole.toml << EOF
  revServers = ["true,${REV_SERVER_CIDR},${REV_SERVER_TARGET},localdomain"]
EOF

cat >> /etc/pihole/pihole.toml << 'TOML_EOF'

[dhcp]
  active = false

[resolver]
  resolveIPv4 = true
  resolveIPv6 = true
  networkNames = true
  refreshNames = "IPV4_ONLY"

[database]
  DBimport = true
  maxDBdays = 365
  DBinterval = 60
  useWAL = true

  [database.network]
    parseARPcache = true
    expire = 365

[webserver]
  domain = "pi.hole"
  acl = ""
  port = "80o,443os,[::]:80o,[::]:443os"

  [webserver.session]
    timeout = 1800
    restore = true

  [webserver.paths]
    webroot = "/var/www/html"
    webhome = "/admin/"

  [webserver.api]
    prettyJSON = false
    pwhash = ""
    cli_pw = true
    maxHistory = 86400
    max_sessions = 64

[files]
  pid = "/run/pihole-FTL.pid"
  database = "/etc/pihole/pihole-FTL.db"
  gravity = "/etc/pihole/gravity.db"
  macvendor = "/etc/pihole/macvendor.db"

  [files.log]
    ftl = "/var/log/pihole/FTL.log"
    dnsmasq = "/var/log/pihole/pihole.log"
    webserver = "/var/log/pihole/webserver.log"

[misc]
  privacylevel = 0
  delay_startup = 0
  nice = -10
  addr2line = true

[debug]
  database = false
  networking = false
  queries = false
TOML_EOF

log_message "Pi-hole TOML configuration created"

# Install Pi-hole v6 unattended
log_message "Installing Pi-hole v6"
retry_command wget -O /tmp/basic-install.sh https://install.pi-hole.net
retry_command bash /tmp/basic-install.sh --unattended

# Install AWS CLI
log_message "Installing AWS CLI"
retry_command snap install aws-cli --channel=v2/candidate --classic

# Wait for AWS CLI to be available
log_message "Waiting for AWS CLI to be available"
sleep 10

# Set the Pi-hole web UI password
log_message "Setting Pi-hole web UI password from Secrets Manager"
if retry_command aws secretsmanager get-secret-value --secret-id $SECRET_ARN; then
    PASSWORD=$(aws secretsmanager get-secret-value --secret-id $SECRET_ARN | jq .SecretString -j)
    /usr/local/bin/pihole setpassword "$PASSWORD"
    log_message "Pi-hole password set successfully"
else
    log_message "WARNING: Failed to retrieve password from Secrets Manager"
fi

# Apply whitelist
log_message "Applying common whitelists"
if retry_command git clone https://github.com/anudeepND/whitelist.git /tmp/whitelist/; then
    python3 /tmp/whitelist/scripts/whitelist.py
    log_message "Whitelist applied successfully"
else
    log_message "WARNING: Failed to apply whitelist"
fi

# Pi-hole v6 configuration is already set via pihole.toml
# No need for post-install CLI configuration commands

# Start and enable Pi-hole FTL service
log_message "Starting Pi-hole FTL service"
systemctl restart pihole-FTL
systemctl enable pihole-FTL

# Wait for service to start
sleep 10

# Verify Pi-hole FTL service is running
log_message "Verifying Pi-hole FTL service status"
if systemctl is-active --quiet pihole-FTL; then
    log_message "Pi-hole FTL is running successfully"
else
    log_message "WARNING: Pi-hole FTL failed to start"
    systemctl status pihole-FTL
fi

# Verify web interface is accessible on port 80
log_message "Verifying Pi-hole v6 web interface accessibility"
sleep 5
if curl -s -f http://localhost/admin/ >/dev/null 2>&1; then
    log_message "Pi-hole v6 web interface is accessible on port 80"
elif curl -s -f http://localhost:8080/admin/ >/dev/null 2>&1; then
    log_message "Pi-hole v6 web interface is accessible on port 8080 (fallback)"
else
    log_message "WARNING: Pi-hole v6 web interface is not accessible"
fi

# Test DNS functionality
log_message "Testing DNS functionality"
if dig @127.0.0.1 google.com +short >/dev/null 2>&1; then
    log_message "DNS functionality test passed"
else
    log_message "WARNING: DNS functionality test failed"
fi

# Display Pi-hole v6 configuration summary
log_message "Pi-hole v6 configuration summary:"
/usr/local/bin/pihole-FTL --config --list 2>/dev/null || log_message "Could not retrieve configuration list"

# Check which ports Pi-hole is listening on
log_message "Checking Pi-hole listening ports:"
netstat -tlnp | grep pihole-FTL || log_message "Could not determine listening ports"

log_message "Pi-hole v6 installation userdata script completed successfully"
